#!/usr/bin/env python

import rpi_ati_net_ft
import time
import math

def main():
    try:
        netft=rpi_ati_net_ft.NET_FT('192.168.11.56')
        netft.set_tare_from_ft()
        print netft.read_ft_http()
        
        netft.start_streaming()
        
        while(True):
            print netft.read_ft_streaming(.1)
        
    except KeyboardInterrupt:
        pass

if __name__ == '__main__':
    main()
